[tool.poetry]
name = "django-dbviews"
version = "0.0.1"
description = ""
authors = ["Keshav Mohta <keshavmohta09@gmail.com>"]
readme = "README.md"
packages = [{include = "django_dbviews"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
